name: "autobuild"
on:
  push:
    tags:
      - 'v*'

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: 234354743961.dkr.ecr.ap-southeast-1.amazonaws.com/gomeow
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: 234354743961.dkr.ecr.ap-southeast-1.amazonaws.com/gomeow
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
            234354743961.dkr.ecr.ap-southeast-1.amazonaws.com/gomeow:latest
          labels: ${{ steps.meta.outputs.labels }}
